---
- name: install system dependencies
  portage: package={{ item }}
  with_items:
    - '>=dev-lang/ruby-2.1.0'  # USE ssl jemalloc
    - '>=dev-ruby/bundler-1.5.2'
    - dev-db/postgresql
    - dev-db/redis
    - dev-libs/libxml2
    - dev-libs/libxslt
    - dev-vcs/git
    - media-gfx/gifsicle
    - media-gfx/imagemagick  # USE hdri jpeg lzma png
    - media-gfx/jhead
    - media-gfx/jpegoptim
    - media-gfx/optipng
    - net-libs/nodejs
    - virtual/jpeg
    - virtual/mta
  when: false  # TODO

- name: create discourse group
  group: >
    name={{ discourse_group }}
    system=yes

- name: create discourse user
  user: >
    name={{ discourse_user }}
    group={{ discourse_group }}
    home={{ discourse_base_dir }}
    createhome=no
    system=yes

- name: prepare directories
  file: >
    state=directory
    path={{ item.path }}
    owner={{ item.owner | default(discourse_user) }}
    group={{ item.group | default(discourse_group) }}
    mode={{ item.mode | default('0755') }}
  with_items:
    - { path: "{{ discourse_base_dir }}" }
    - { path: "{{ discourse_logs_dir }}" }
    - { path: "{{ discourse_base_dir }}/tmp", mode: '0700' }
    - { path: "{{ discourse_conf_dir }}", owner: 'root', group: 'root' }

- name: make symlinks to default locations
  file: >
    state=link
    src={{ item.src }}
    dest={{ item.dest }}
    force=yes
  with_items:
    - { src: "{{ discourse_logs_dir }}", dest: "{{ discourse_base_dir }}/log" }
    - { src: /var/run/discourse, dest: "{{ discourse_base_dir }}/tmp/pids" }

- name: install runscript
  copy: >
    src=runscript
    dest=/etc/init.d/discourse
    owner=root group=root mode=0755

- include: install_discourse.yml
  sudo: yes
  sudo_user: "{{ discourse_user }}"

- name: install plugins
  sudo: yes
  sudo_user: "{{ discourse_user }}"
  git: >
    repo="{{ item.repo }}"
    dest="{{ discourse_base_dir }}/plugins/{{ item.name }}"
    version="{{ item.rev | default(item.version) }}"
    update=true
    force=true
  with_items: discourse_plugins
  notify: restart discourse
